### ISSUE TITLE
Make Changes column key tab

### ISSUE THREAD

**Issue by JIMANOPE** [TatuLund/GridFastNavigation#10]
Good morning from Colombia,

I sent you a link of the demo, so you can help me: columns 3 to 7 in each row are added in column 8, but it is not possible to perform when changing columns with the tab key is only possible by changing row or pressing Enter

http://35.163.165.96:8080/GridFastNavigation-demo-0.2.1/

I need your help. Thank you.

**Comment by thinwire** [comment]
Ah, it took me a while to understand what you meant, but yes: it appears that value change events aren't being properly sent when navigating using tab/shift+tab, only when changing rows using enter/shift+enter. As such, column 8 isn't being updated when using tab navigation.

I'll see what I can do.

**Comment by TatuLund** [comment]
The value change events were implemented in version 0.3.0. The enter key behavior configuration option was added to version 0.5.2.
