### ISSUE TITLE
RowEditListener not working

### ISSUE THREAD

**Issue by nisensee** [TatuLund/GridFastNavigation#11]
Version: 0.2.1

Back in "the olden days" (Version 0.1.x) there was but one event listener, the _FastNavigationListener_. One of it's features was "only propagate update events, be silent if the user is just 'skipping rows'".

Nowadays there are many event listeners for all kinds of purposes. Which I think is a good thing. Alas, the one dedicated to "actual updates", the _RowEditListener_ appears to be broken. Or I misunderstood it's purpose. Also entirely possible.

Check out the [0.2.1 online demo](http://patrik.app.fi/GridFastNavigation-demo-0.2.1/). In _DemoUI:100_ you add a new _RowEditListener_. Thus I would expect that printChangedRow() in DemoUI:168 gets triggered once I update a row ( writeOutput("Row " + rowIndex + " changed to: " + sb.toString());). 
However, I never receive these events. 
![noupdate](https://cloud.githubusercontent.com/assets/2082077/21050020/95afb942-be18-11e6-966b-20b435861a70.png)

I can "workaround" that issue by utilizing the _EditorCloseListener_ BUT it can not distinguish between a "skip" and a "change". Which kind of brakes the original addon's intend :)

**Comment by thinwire** [comment]
Damn. I knew there was _something_ I missed. :D
Unfortunately, the original feature relied on some rather convoluted (and leaky) logic to detect these changes. I'll try to add some kind of change detection in the next version.

**Comment by TatuLund** [comment]
I am in process of making release this week, with this one fixed.

**Comment by TatuLund** [comment]
Fixed in 0.3.0
