### ISSUE TITLE
Keyboard on iPad not displayed when editing rows

### ISSUE THREAD

**Issue by neerup** [TatuLund/GridFastNavigation#114]
I know this is a stretch, but here goes... 
 
We are using latest version of the GridFastNavigation Add-on, alot of our users use iPads
But when they click a row to edit and the row opens, the soft keyboard is not displayed, on pc's and mac's the first open field in the open gridline is selected, so I think the keyboard should popup on iPad, but it doesn't.
I know that Vaadin 8 is EOL but **we are evaluating the possibility to buy the Extended support license.**
We can see the demo https://tatu.app.fi/GridFastNavigation-demo-2.5.3/ has the same Issue.

Is there any chance that this Issue is solved in the latest Vaadin version (with Extended support license) ?
Can You validate that the keyboard will show with the latest version?
If it is solved, we'll have alot more reason for updating to the new licsense.

**Comment by johannest** [comment]
In an iPhone (iOS 17.4.1) single tap does not yet bring up the soft keyboard, I need to double tap such that the text/number is selected before the keypad appears for me.

**Comment by neerup** [comment]
> In an iPhone (iOS 17.4.1) single tap does not yet bring up the soft keyboard, I need to double tap such that the text/number is selected before the keypad appears for me.

Are You testing on the latest Vaadin 8.25.2?

**Comment by johannest** [comment]
I tested the demo from the link you provided. It seems to be rather old version V8.9.0.. Did you observe the same issue with latest V8?

**Comment by johannest** [comment]
I can try it out with latest Vaadin 8. Edit: looks like it has the same issue

**Comment by neerup** [comment]
> I tested the demo from the link you provided. It seems to be rather old version V8.9.0.. Did you observe the same issue with latest V8?

We are running on the lates 8.14.3 but would like to know if it works on 8.25.2 (Extended Maintenance)

**Comment by TatuLund** [comment]
Check if version 2.6.4 of the add-on works better. I did small adjustment regarding timing of the focus and text selection calls.

**Comment by johannest** [comment]
Did not help. I even tried the following, but the same issue with iOS
```
Scheduler.get().scheduleFixedDelay(() -> {
                            EditorWidgets.selectAll(ew);
                            return false;
                                }, 200
                        );
```

**Comment by neerup** [comment]
Thanks for the effort guys.. I will try to sell the "click in the open field to show keyboard" functionality :) one could argue that it is a feature not disturb the user with keyboard every time he/she selects a row to select an option... So thanks... Lets close the issue
