### ISSUE TITLE
Support for Vaadin 7.7.7

### ISSUE THREAD

**Issue by polacjur** [TatuLund/GridFastNavigation#12]
Addon is not working in Vaadin 7.7.7. Are you going to support this version ?
I tried your demo, in pom I changed vaadin to version 7.7.7 and I got errors when i executed `mvn jetty:run`

Error message:

> [INFO]       [ERROR] Errors in 'jar:file:/C:/Users/Juraj/.m2/repository/org/vaadin/patrik/GridFastNavigation/0.2.1/GridFastNavigation-0.2.1.jar!/org/v
> aadin/patrik/client/GridViolators.java'
> [INFO]          [ERROR] Line 47: Referencing field 'com.vaadin.client.widgets.Grid.Editor.focusedColumnIndex': unable to resolve field in class 'com.v
> aadin.client.widgets.Grid.Editor'
> [INFO]    [ERROR] Aborting compile due to errors in some input files

**Comment by TatuLund** [comment]
This is fixed in version 0.4.0
