### ISSUE TITLE
CellEditListener won't trigger

### ISSUE THREAD

**Issue by bandris** [TatuLund/GridFastNavigation#13]
### symptom
I hope I'm wrong, but as I see there is no example for "addCellEditListener" and its usage.
I try to use it but it never trigger the event.

### problem
Btw, my problem is that if I left a cell empty, when I navigate to another cell in this row, the editor filled with "null" value, even if I catch it in cell focus listener and set the value to 0 for example.

### sidenote
It would be better if I can use the editor converters or null representation stuffs, but as I see I cant configure the editor fields.

**Comment by TatuLund** [comment]
I am in process of making release this week, with this one fixed.

**Comment by TatuLund** [comment]
Fixed in 0.3.0
