### ISSUE TITLE
New contributions

### ISSUE THREAD

**Issue by JIMANOPE** [TatuLund/GridFastNavigation#15]
Hi patrick, Thanks for the improvements made. I have two new contributions:
1. When I am in the last row I want the focus to go to the next column first row enter key.
2. Allow summary of columns setEditable(false); By pressing the enter key to the next column. 
   Example
   **Add code in method initGrid**
   grid.getColumn("col7").setEditable(false);

   **Add code in method printChangedRow**
   int sum = Integer.valueOf(ds.getItem(itemId).getItemProperty("col3").getValue().toString())
                + Integer.valueOf(ds.getItem(itemId).getItemProperty("col4").getValue().toString())
                + Integer.valueOf(ds.getItem(itemId).getItemProperty("col5").getValue().toString())
                + Integer.valueOf(ds.getItem(itemId).getItemProperty("col6").getValue().toString());

        ds.getItem(itemId).getItemProperty("col7").setValue(sum);

  Thanks

**Comment by TatuLund** [comment]
1. This sounds natural and should not be hard to add that feature. Thanks for the hint.

2. This thing I think outside of the scope of this add-on. It is very application specific which columns should be added up (or performed other types of calculation etc.) Also from perspective of separation of concern this should be implemented in the Model (refer to MVP paradigm). So I would implement calculations directly in model class to the underlying container and just set the summary column not editable.

**Comment by TatuLund** [comment]
I added implementation 1. to version 0.5.4

**Comment by JIMANOPE** [comment]
Hi patrick, Thanks for implementation.
