### ISSUE TITLE
Need ability to programatically close editor from server side.

### ISSUE THREAD

**Issue by bsutton** [TatuLund/GridFastNavigation#20]
I'm trying to add a method to add a new row to the grid.

The problem is that if the editor is open when I add the new row the whole UI locks up.

So I thought the best method to fix this was to close the editor from the server side.

I exposed the 'closeEditor' method via a server side rpc. But the editor still doesn't close.

What is the correct method to close the editor?

**Comment by TatuLund** [comment]
I think Grid.getEditor().cancel() should do that, so no need to add this to this add-on.

**Comment by TatuLund** [comment]
This works.
