### ISSUE TITLE
Add support for 'action buttons'

### ISSUE THREAD

**Issue by bsutton** [TatuLund/GridFastNavigation#24]
I have a requirement to allow a user to delete rows in the grid.

I've added a 'delete' button into a cell in the grid and it almost works.
The delete button allows me to click and delete a row, the problem is that it then puts me into edit mode on the current row (that is the current row after the grid rows collapse up into the deleted row as expected).

How do I stop the row going into edit mode when I click a button.

Supporting this mode seems generically useful for any set of action buttons in a row.

**Comment by TatuLund** [comment]
I will close this one too, since DeleteButtonRenderer solves the problem.
