### ISSUE TITLE
Uneditable rows in Grid

### ISSUE THREAD

**Issue by vjetname** [TatuLund/GridFastNavigation#27]
Hi,
I need some option to deny to open editor on some rows in grid -> I need some uneditable rows in grid.

I tried some workaround with disabling all the columns on the row, but it doesn't work well. Actually the navigation over the grid crashes on row like that, or focus goes to some editor component (more accurately to the comboBox field of ExtendedTokenField https://vaadin.com/directory#!addon/extended-token-field, which I use).

I still need to be able to select that row, but without editing it.

Do you think you can help me somehow?
Thank you for your answer.
Milan

**Comment by AlexByte** [comment]
Disabling all columns works.

**Comment by TatuLund** [comment]
> Disabling all columns works.

It is actually not working, because of a bug. But I have fixed it now, it will be in version 2.3.2, I am adding also disableAllColumns convenience method to EditorOpenEvent.

**Comment by TatuLund** [comment]
Version 2.3.2 is released in directory

**Comment by TatuLund** [comment]
See also: https://github.com/vaadin/framework/issues/11002

**Comment by AlexByte** [comment]
@TatuLund What bug?

**Comment by TatuLund** [comment]
@AlexByte it was possible that when there were no editable columns when opening the editor, the client side ended in eternal loop and hence not respond. At least that bug was rather consistently happening to me.
