### ISSUE TITLE
RowFocusEvent should contain info for Header/Body/Footer

### ISSUE THREAD

**Issue by evanzel** [TatuLund/GridFastNavigation#33]
Hi,
As an enhancement, it would be useful if the RowFocusEvent could provide information as to whether the returned focused rowIndex is in the header, the body, or the footer.
Thanks.

**Comment by TatuLund** [comment]
At the moment row focus tracking happens only in the body.

**Comment by TatuLund** [comment]
Version 1.1.6 has been modified so that Row/CellFocusEvents return row index -1 when in Footer/Header (Vaadin 7). Same modification will be in Version 2.1.6 later (Vaadin 8)

**Comment by evanzel** [comment]
That helps a lot, thanks!

**Comment by TatuLund** [comment]
Version 2.1.6 has been released as well.

@evanzel I would appreciate your feedback and rating of the add-on here: https://vaadin.com/directory/component/gridfastnavigation-add-on
