### ISSUE TITLE
Row duplication in default widgetset xml at compile time

### ISSUE THREAD

**Issue by DuffMck** [TatuLund/GridFastNavigation#40]
Hi,

as you can see at [this thread](https://vaadin.com/forum/#!/thread/156459/158691) on Vaadin forum, there is a common bug of its widgetset builder. It searches the string "widgetset" inside the file name of [your xml file](https://github.com/TatuLund/GridFastNavigation/blob/master/GridFastNavigation-addon/src/main/resources/org/vaadin/patrik/GridFastNavigation.gwt.xml), and if it doesn't find anything it duplicates this row every time:

`  <inherits name="org.vaadin.patrik.GridFastNavigation"/>`

so could you change your xml file name to avoid this behaviour?

Thanks!

**Comment by TatuLund** [comment]
Yes, I knew this is happening with the demo application, but I did not know it happens with apps using the add-on. It is weird issue with maven, and I do not yet know why it is happening. My setup with Renderers collection add-on is practically identical, and it works correctly.

**Comment by TatuLund** [comment]
2.1.7 is now available in Directory.
