### ISSUE TITLE
Widgetset compilation every time

### ISSUE THREAD

**Issue by jmrunge** [TatuLund/GridFastNavigation#41]
Hi, 
Since I added your addon to my project, my widgetset gets compiled every single time I build the project. This didnt happened before (and should not happend). Can you take a look at this? Its quite annoying and time consuming. 
Im using Vaadin 8.1.6.
Thanks!

**Comment by TatuLund** [comment]
Yes, I knew this is happening with the demo application, but I did not know it happens with apps using the add-on. It is weird issue with maven, and I do not yet know why it is happening. My setup with Renderers collection add-on is practically identical, and it works correctly.

**Comment by jmrunge** [comment]
Im using other addons and its not happening there. Anything I can do to help troubleshoot, just tell me!

**Comment by jmrunge** [comment]
Based on #40  I tried cloning your project and changing GridFastNavigation.gwt.xml to GridFastNavigationWidgetSet.gwt.xml (both the file name and in POM.xml) solves this issue and #40

**Comment by TatuLund** [comment]
Yes, I can confirm this. I had totally overlooked that minor detail.

**Comment by jmrunge** [comment]
Cool! Glad to help!

**Comment by TatuLund** [comment]
Yes, thanks alot for spotting this. I uploaded new version to Directory.

**Comment by DuffMck** [comment]
Could you merge your commits on master branch too?

Thanks!

**Comment by TatuLund** [comment]
Yes, a moment. That goes to version 1.1.7 for Vaadin 7.

**Comment by DuffMck** [comment]
Thanks a lot! Very kind and fast!

**Comment by TatuLund** [comment]
Thanks. I would appreciate your rating and feedback in the directory, vaadin.com/directory/component/gridfastnavigation-add-on
