### ISSUE TITLE
Widgetset compilation exception

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#48]
> An internal compiler exception occurred
> com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
> at com.google.gwt.dev.js.ast.JsVisitor.translateException(JsVisitor.java:482)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:469)
> at com.google.gwt.dev.js.ast.JsModVisitor$NodeContext.traverse(JsModVisitor.java:153)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAccept(JsModVisitor.java:176)
> at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
> at com.google.gwt.dev.js.ast.JsInvocation.traverse(JsInvocation.java:88)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> at com.google.gwt.dev.js.ast.JsModVisitor$NodeContext.traverse(JsModVisitor.java:153)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAccept(JsModVisitor.java:176)
> at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
> at com.google.gwt.dev.js.ast.JsVars$JsVar.traverse(JsVars.java:64)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> at com.google.gwt.dev.js.ast.JsModVisitor$ListContext.traverse(JsModVisitor.java:80)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAcceptWithInsertRemove(JsModVisitor.java:197)
> at com.google.gwt.dev.js.ast.JsVisitor.acceptWithInsertRemove(JsVisitor.java:121)
> at com.google.gwt.dev.js.ast.JsVars.traverse(JsVars.java:104)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> at com.google.gwt.dev.js.ast.JsModVisitor$ListContext.traverse(JsModVisitor.java:80)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAcceptWithInsertRemove(JsModVisitor.java:197)
> at com.google.gwt.dev.js.ast.JsVisitor.acceptWithInsertRemove(JsVisitor.java:121)
> at com.google.gwt.dev.js.ast.JsBlock.traverse(JsBlock.java:53)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> at com.google.gwt.dev.js.ast.JsModVisitor$NodeContext.traverse(JsModVisitor.java:153)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAccept(JsModVisitor.java:176)
> at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
> at com.google.gwt.dev.js.ast.JsFunction.traverse(JsFunction.java:181)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> at com.google.gwt.dev.js.ast.JsModVisitor$NodeContext.traverse(JsModVisitor.java:153)
> at com.google.gwt.dev.js.ast.JsModVisitor.doAccept(JsModVisitor.java:176)
> at com.google.gwt.dev.js.ast.JsVisitor.accept(JsVisitor.java:109)
> at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.processNativeMethod(GwtAstBuilder.java:3230)
> at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1577)
> at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:360)
> at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
> at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3916)
> at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3954)
> at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
> at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
> at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:546)
> at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
> at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
> at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
> at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
> at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
> at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
> at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
> at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
> at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
> at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
> at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
> at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
> at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
> at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
> at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
> at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
> at com.google.gwt.dev.Compiler.main(Compiler.java:125)
> Caused by: java.lang.ClassCastException: com.google.gwt.dev.jjs.ast.JClassType cannot be cast to com.google.gwt.dev.jjs.ast.JInterfaceType
> at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:160)
> at com.google.gwt.dev.jjs.impl.ReferenceMapper.createMethod(ReferenceMapper.java:246)
> at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:110)
> at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor$JsniReferenceCollector.endVisit(GwtAstBuilder.java:315)
> at com.google.gwt.dev.js.ast.JsNameRef.traverse(JsNameRef.java:113)
> at com.google.gwt.dev.js.ast.JsVisitor.doTraverse(JsVisitor.java:467)
> ... 54 more
> at GridViolators.java(38): escallator.@com.vaadin.client.widgets.Escalator::getBody()
> com.google.gwt.dev.js.ast.JsNameRef
> at GridViolators.java(38): escallator.@com.vaadin.client.widgets.Escalator::getBody()()
> com.google.gwt.dev.js.ast.JsInvocation
> at GridViolators.java(38): conBody = escallator.@com.vaadin.client.widgets.Escalator::getBody()()
> com.google.gwt.dev.js.ast.JsVars$JsVar
> at GridViolators.java(38): var conBody = escallator.@com.vaadin.client.widgets.Escalator::getBody()()
> com.google.gwt.dev.js.ast.JsVars
> at GridViolators.java(33): {
> var cfh = grid.@com.vaadin.client.widgets.Grid::cellFocusHandler;
> var row = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::rowWithFocus;
> var contWithFocus = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::containerWithFocus;
> var escallator = grid.@com.vaadin.client.widgets.Grid::getEscalator()();
> [...]
> }
> 
> com.google.gwt.dev.js.ast.JsBlock
> at GridViolators.java(33): function(grid){
> var cfh = grid.@com.vaadin.client.widgets.Grid::cellFocusHandler;
> var row = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::rowWithFocus;
> var contWithFocus = cfh.@com.vaadin.client.widgets.Grid.CellFocusHandler::containerWithFocus;
> var escallator = grid.@com.vaadin.client.widgets.Grid::getEscalator()();
> [...]
> }
> 
> com.google.gwt.dev.js.ast.JsFunction
> at GridViolators.java(33): public static final native int getFocusedRow(Grid<?> grid);
> org.eclipse.jdt.internal.compiler.ast.MethodDeclaration

**Comment by TatuLund** [comment]
Are you also using Gradle? See this one: https://github.com/TatuLund/GridFastNavigation/issues/46

**Comment by AlexByte** [comment]
Yes
