### ISSUE TITLE
Ability to enable full row validation

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#51]
Now only the current column is validated.

**Comment by TatuLund** [comment]
This is coming from how Grid's un-buffered editor works by default.

**Comment by AlexByte** [comment]
Can you change the behavior when the option is enabled?

**Comment by TatuLund** [comment]
I have added two validators in v8 demo app. If you edit one column and get validation error, it is possible to change a column, and if you get validation error in other column as well, you will see both validation error messages. Isn't that how it should be?

**Comment by AlexByte** [comment]
Now validated only edited cells. How to trigger validation of all cells in row when trying to switch to another row?

**Comment by TatuLund** [comment]
At the moment it should not allow to change the row, at least that is is how it works in my case.

**Comment by AlexByte** [comment]
Now validated only edited cells, but not edited cells can be null and not valid.

**Comment by TatuLund** [comment]
Do you mean the following case: For some other reason than editing (e.g. programmatic change, initial value) there is value on the row, that does not pass validation, and hence forced validation is needed?

**Comment by AlexByte** [comment]
Yes.

**Comment by TatuLund** [comment]
@AlexByte I think we have solution, check discussion in #51.

**Comment by TatuLund** [comment]
Version 2.2.2 is in Directory

**Comment by AlexByte** [comment]
@TatuLund I want to validate all columns only on changing row.

**Comment by TatuLund** [comment]
Test version 2.2.3, it is now in Directory

**Comment by TatuLund** [comment]
The functionality has been improved in version 2.3.7
