### ISSUE TITLE
Pressing Esc is not reverting value

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#52]
Test with Vaadin 8.3.1
GridFastNavigation version 2.1.10

**Comment by TatuLund** [comment]
Thanks for reporting, however this works for me. I.e. I can't replicate the issue.

**Comment by TatuLund** [comment]
Which OS and Browser you are using? I tested Windows 10, Edge, IE11, FF & Chrome and they all work ok.

**Comment by AlexByte** [comment]
Try this demo https://github.com/AlexByte/gs-crud-with-vaadin

**Comment by TatuLund** [comment]
I did first brief check with my demo app, using the extension same way as you do, i.e. https://github.com/AlexByte/gs-crud-with-vaadin/blob/master/complete/src/main/java/hello/VaadinUI.java#L43 just adding it to Grid and not enabling any listeners etc. Still it works. So at least that is not the reason.

It may take a while to check your and setup your test app https://github.com/AlexByte/gs-crud-with-vaadin

**Comment by AlexByte** [comment]
Your demo application uses Vaadin 7.

**Comment by TatuLund** [comment]
The Vaadin 8 version is here: https://github.com/tatulund/gridfastnavigation/tree/vaadin8

**Comment by AlexByte** [comment]
OK

**Comment by AlexByte** [comment]
Setting up my test app is easy: `cd complete & mvn jetty run`.

**Comment by AlexByte** [comment]
I found out the reason: you set up ValueChangeMode.BLUR for TextField.

**Comment by TatuLund** [comment]
Thanks for pointing that out.

**Comment by TatuLund** [comment]
I found a fix for this. The blur - focus cycle needed to be added to value setting of the text field. Patch is coming. Thanks for your support.

**Comment by TatuLund** [comment]
V7 version was not impacted by this (this was migration regression), this closing.
