### ISSUE TITLE
ClickOutListener not working

### ISSUE THREAD

**Issue by AlexByte** [TatuLund/GridFastNavigation#54]
In demo its working, but not in my app.

**Comment by TatuLund** [comment]
> In demo its working, but not in my app.

That makes it difficult to find out why it is so. The feature may have some limitations, since it is implemented by calculating that there is click happening outside Grid coordinates, i.e. outside the rectangle of the Grid. 

Could you describe in more detail how it is not working.

**Comment by AlexByte** [comment]
Here is the code I use:

        FastNavigation fastNavigation = new FastNavigation(grid;
        fastNavigation.addClickOutListener(clickOutEvent -> {
            Notification.show("OutListener");
        });

**Comment by TatuLund** [comment]
This may be timing issue regarding when to add the listener. I think you need to add the listener before you add grid to layout.

**Comment by TatuLund** [comment]
No, actually I found minor bug. You need to instantiate FastNavigation with constructor public FastNavigation(final Grid<T> g, boolean changeColumnOnEnter, boolean dispatchEditEventOnBlur) with dispatchEditEventOnBlur = true, in order to addClickOutListener(..) work properly.

**Comment by TatuLund** [comment]
Thanks for pointing me to investigate this (and those couple of other things). There has been couple of similar issues with interdependencies of the features before as well. The add-on has become quite complex. This was rather easy to fix as well. I will upload fixed version soon to Directory.

**Comment by TatuLund** [comment]
I would appreciate your rating & feedback of the add-on in the Directory, https://vaadin.com/directory/component/gridfastnavigation-add-on
