### ISSUE TITLE
WidgetHandlers for custom widgets

### ISSUE THREAD

**Issue by yoshie82** [TatuLund/GridFastNavigation#58]
Is there any reason, why EditorWidgets#registerHandler is private?

Would be much easier (less magic), if this would be public or at least package private

**Comment by TatuLund** [comment]
No, there is no specific reason for that. So if I understand right, it would be desired, that it is possible to extend EditorWidgets and use the extended version instead. I think it is well justified idea. Is there something else needed for that? I need to investigate it a bit more. Also if there are some framework stock fields, that needs to be added there, open issues about those.

**Comment by yoshie82** [comment]
I don't think that it is necessary to extend EditorWidgets itself.. It would be enough, if I can call that method with a non-native call (from java).

I don't know the inheritance strategies in gwt/js, but perhaps it is possible to implement a kind of "bestCandidate" for abstract classes. 
e.g. you could use ValueBoxBase instead of VTextField
On the first call you could look for a candidate that is assignable from the concrete class and save this candidate for the next call !?

**Comment by TatuLund** [comment]
I uploaded version 2.1.8 which has EditorWidgets#registerHandler public and improved JavaDocs. Tell me if it works for you.
