### ISSUE TITLE
Disable Editor-Widgets

### ISSUE THREAD

**Issue by yoshie82** [TatuLund/GridFastNavigation#59]
I'm not sure, if this is a bug, or just own disability ^^

I want to disable an editor-widget under some circumstances. I added an OpenListener to the editor to check the condition and disable the CheckBox
````java
getEditor().addOpenListener(event -> {
            boolean enabled = !event.getBean().isRequired();
            activeCheckBox.setEnabled(enabled);
        });
````
But even if the CheckBox should be disabled, the EditorStateManager enables the CheckBox in the #waitForEditorOpen-> complete() Method of the Callback, because this column is not in the disabledColumns

Is there any other possibility to disable this CheckBox ?!

**Comment by TatuLund** [comment]
I think this discussion here is pretty much about the same thing. There are couple of ways to do this. One of them is to use event.disableColumns() method. 

https://github.com/TatuLund/GridFastNavigation/issues/55

**Comment by yoshie82** [comment]
ah ok =)
hadn't seen this. thx 
-- can be closed

**Comment by TatuLund** [comment]
No problem.
