### ISSUE TITLE
Overlay of icon

### ISSUE THREAD

**Issue by ky2ninh** [TatuLund/GridFastNavigation#61]
![image](https://user-images.githubusercontent.com/6173892/38941911-347d540c-42f3-11e8-8a48-89392ea08d04.png)
![image](https://user-images.githubusercontent.com/6173892/38941933-39b647bc-42f3-11e8-8a74-c222e947c1b3.png)
First image is of a Vaadin 8.3.1 Grid without FastNavigation. Second is with FastNavigation. The trash can icon in the second the not visible.

**Comment by TatuLund** [comment]
The trash can icon is not visible, since editor row is enabled on that row, and Renderers are not applied for editor row. This is generic feature in Grid and not related to FastNavigation add-on.

**Comment by TatuLund** [comment]
This question popups occasionally in many places, like here: 
https://github.com/vaadin/framework/issues/10780
