### ISSUE TITLE
Selecting ComboBox item outside grid quits edit mode

### ISSUE THREAD

**Issue by apgsga-stb** [TatuLund/GridFastNavigation#62]
I have a grid, extended with FastNavigation, configured with `dispatchEditEventOnBlur = true`. One column of the grid is edited thru a ComboBox. If this ComboBox has many items, it's possible that it's selection list overlaps the grid's border. If I select an item outside the grid's border with the mouse, the edit mode is closed and no item is selected.

My workaround for the moment is `dispatchEditEventOnBlur = false`, but if you had a solution other than that, I'd be very happy :-).

**Comment by TatuLund** [comment]
This is fixed by https://github.com/TatuLund/GridFastNavigation/commit/e0139460513b09e14d7a508ab30e5417d8a16948 just update the add-on to the latest version.
