### ISSUE TITLE
Entering numbers with dedicated number block results in letters instead of numbers

### ISSUE THREAD

**Issue by apgsga-stb** [TatuLund/GridFastNavigation#63]
I have a grid with an editable column where I can enter only numbers. Now, if I focus on that cell and push '4' on my keyboard (the one above 'e' and 'r'), the grid goes automatically in edit mode and the entered '4' appears in the cell. That's cool.

Now I have a keyboard with a separated number block. If I NumLock it and do the same with the '4' on the number block. Guess what? I get a 'd' instead of '4'. Funny, isn't it?

**Comment by TatuLund** [comment]
Thanks for good observation. I think I found the reason.

**Comment by TatuLund** [comment]
I uploaded the version 2.1.19 to directory
