### ISSUE TITLE
RowEditEvent fired after ESC-key

### ISSUE THREAD

**Issue by mirkoliver** [TatuLund/GridFastNavigation#64]
From my understanding, RowEditEvents should only be fired, when something has changed.
Now when clicking in one cell, nothing changing there, then using ESC-key to leave the editor and then clicking into another cell, a RowEditEvent is fired.

**Comment by TatuLund** [comment]
I think I managed to fix this, the version 2.1.20 is in Directory. Please report if there are regressions.

**Comment by mirkoliver** [comment]
Yes, this works! Great, thanks!
