### ISSUE TITLE
ComboBox doesn't show any entries

### ISSUE THREAD

**Issue by apgsga-stb** [TatuLund/GridFastNavigation#66]
Scenario: Grid is enhanced with GridFastNavigation. `dispatchEditEventOnBlur` is enabled. The grid contains a column with an editable ComboBox.

Now, do the following:
1. enter edit mode
2. enter a value that does not match any entry of the ComboBox
3. click outside the grid -> stops editing
4. enter edit mode again
5. try to select a value by clicking on the comboboxes' down arrow -> no values are shown

Code example:

```java
public class FastNavigationUI extends UI {
	@Override
	protected void init(VaadinRequest request) {
		Grid<Todo> grid = new Grid<>();
		grid.setItems(new Todo("One"), new Todo("Two"));
		grid.setHeightByRows(3);
		
		new FastNavigation<>(grid, false, true);

		ComboBox<String> typeField = new ComboBox<>();
		typeField.setItems("One one one one one",
				"Two two two two two two", 
				"Three three three three three three three three", 
				"Four four four four four", 
				"More (outside table area)");
		grid.addColumn(Todo::getType).setEditorComponent(typeField, Todo::setType).setExpandRatio(1);

		grid.getEditor().setEnabled(true);
		grid.getEditor().setBuffered(false);
		setContent(grid);
	}

	private static class Todo {
		private String type;

		public Todo(String type) {
			this.type = type;
		}

		public String getType() {
			return type;
		}

		public void setType(String type) {
			this.type = type;
		}
	}
}

```

**Comment by TatuLund** [comment]
I tried to replicate the issue with the demo app of the add-on, but I could not. Do you mean that the ComboBox popup is empty?

**Comment by apgsga-stb** [comment]
Exactly. See the attached "tutorial".

[issue_#66.pdf](https://github.com/TatuLund/GridFastNavigation/files/1973586/issue_.66.pdf)

**Comment by TatuLund** [comment]
I see. The symptoms seem to be very similar than reported here: https://github.com/vaadin/framework/issues/9915

**Comment by TatuLund** [comment]
I recommend you to upgrade to Vaadin 8.4.0 and try again. We have introduced bunch of bug fixes to ComboBox lately.

**Comment by apgsga-stb** [comment]
Yeah! That's what I'm working on just now :-)

I'll report the result here.

**Comment by apgsga-stb** [comment]
\(^_^)/

It works.
