### ISSUE TITLE
Quick-Delete value

### ISSUE THREAD

**Issue by nisensee** [TatuLund/GridFastNavigation#7]
It might be useful if a user could quick-delete a cell-value by pressing _del_ or _backspace_. The former could delete+autocommit the value whereas the later deletes the value and starts the edit-mode. Just as Excel does.

**Comment by thinwire** [comment]
Added to feature list for next version

**Comment by TatuLund** [comment]
I studied this item. I understand your reqest as follows. If I start typing with Delete key, the value of the focused cell is deleted. Backspace is reserved for browsing back. However with Delete key this should be possible.

**Comment by TatuLund** [comment]
This is included in v0.5.6
