### ISSUE TITLE
Set cell focus programmatically

### ISSUE THREAD

**Issue by mirkoliver** [TatuLund/GridFastNavigation#70]
Is there a chance to set cell focus programmatically?

**Comment by TatuLund** [comment]
In practice, this does not differ from #68

**Comment by mirkoliver** [comment]
I've not described it well.

#70 deals with setting the cell focus and immediately entering the cell editor.
#68 only deals with setting the cell focus without entering editor.

**Comment by TatuLund** [comment]
Check version 2.3.4 for setFocusedCell(..) method
