### ISSUE TITLE
Save the whole Row

### ISSUE THREAD

**Issue by jamariSetual** [TatuLund/GridFastNavigation#72]
I notcie that you add the method 'setRowValidation', but I don't get how to validate the row. 

My UseCase:

I would like to validate the whole Row (itemId, editItem) once before the editor closed. I only find solutions that triggers all changes in all Columns, but I only want to validate the itemId at the end. If there are some commit-errors i would like to see than in the editRow, so closing the editor must be stopped. 
I think i need a method called just before closeEditor is called.

**Comment by TatuLund** [comment]
I also think the current solution in the add-on is not perfect. It is somewhat ok for the purpose.

A fundamental problem is that Editor clears _all_ validation notifications when you edit. And that leaves some holes in the logic. I think it is a bug in Editor, or some sort of flaw. I have been thinking possible workarounds, but at the moment I do not have one.

If I get an good idea, I may improve the functionality.

**Comment by jamariSetual** [comment]
I checked out your project and starting to analyse your code and the way the editor on the client works. I see the problems you have.

May I have to mark the row as not saved to DB, in that case I could use EditorClose-Event.

*Thinking*

**Comment by jamariSetual** [comment]
So, I took some time to find a workarround. First test are successful, so this workarround is doing nearly what i want.

Save Row after editor close.

nav.addEditorCloseListener(e -> { 
....try {
........if(e.wasCancelled()) { 
............return;
........}
......../* code to save */
....} catch (CommitException e1) {
........e1.printStackTrace();
......../* error dialog or notification */
....}
});

Add a Validator to a field of your choice. This Validator will validate the whole data on teh FieldGroup

getColumn(propertyId).getEditorField().addValidator(new FieldGroupValidator<>(grid));

The FieldGroupValidator is only passing the current FieldGroup to the validateMethod. 

It works, unless one issus I have to do futher investigation:

... - It seems that a error from the Field will block the focus on that field. That would make it impossible to change the data somewhere else to correct the data (Keys are block, mouse-clicks are working)

Another Topic. When i edit a textfield and i use The keys POS1 or END to move to the beginning of the text field, the grid-cursor will move to the first row. Can I disable POS1 and END - Shortcuts?

**Comment by TatuLund** [comment]
I made an improvement to the setRowValidation(true) in version 2.3.7. 

> A fundamental problem is that Editor clears all validation notifications when you edit

There is somewhat working workaround to this problem.
