### ISSUE TITLE
Disabled columns are overwritten in EditorOpenEvent

### ISSUE THREAD

**Issue by yoshie82** [TatuLund/GridFastNavigation#73]
Why  'disabledColumns' in EditorOpenEvent is implemented as an array?! 

There is only 1 event for all listeners
````java
        EditorOpenEvent<T> ev = new EditorOpenEvent<>(g, rowIndex, colIndex, item);
        editorOpenListeners.dispatch(ev);
````
If you need independent EditorOpenListeners, following is not possible:
````java
        List<Grid.Column<Pojo, ?>> columns = grid.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            int disabled = i;
            extension.addEditorOpenListener(event -> event.disableColumns(disabled));
        }
````
I would expect, that all columns would be disabled, but only the last one is.
Of course a workaround would be to handle already disabled columns, but ... *mhmm...*

btw: thx for fixing the issue when disabling all columns ^^

**Comment by TatuLund** [comment]
There are two ways to disable the columns via this event.

Either you disable all columns with event.disableAllColumns() method, which was added lately for convenience. Based your code example you are trying to achieve this.

You can also disable selected columns by listing them, like event.disableColumns(1,3,5,7) or something like that.

**Comment by yoshie82** [comment]
that was just an example (i would never add a listener for every column ^^)... in a grid with 10 columns i want to disable 2 or 3 from different modules, so i need different listeners.
for the moment i use a workaround. put the existing disabled column in a list, add my new disabled columns and set them back to the event...

but it would be much easier to use a set / sorted set for that and i couldn't see any reason for an array.

**Comment by TatuLund** [comment]
You can easily use Set and pass it as array like this:

```
			Set<Integer> columns = new HashSet<>();
			columns.add(1);			
			columns.add(3);			
			event.disableColumns((Integer[]) columns.toArray());

```

**Comment by yoshie82** [comment]
i know ;)
i think you don't know what i mean?! it would be much easier if the field would be a set, so different listeners can just call "event.disableColumns(x, y, z)" and these columns are added and not replaced.

necessary workaround for the moment
````java
    protected static void disableColumns(EditorOpenEvent<?> event, Collection<Integer> disabled) {
        SortedSet<Integer> newDisabled = Sets.newTreeSet(Comparator.naturalOrder());
        Collections.addAll(newDisabled, MoreObjects.firstNonNull(event.getDisabledColumns(), new Integer[0]));
        newDisabled.addAll(disabled);
        event.disableColumns(newDisabled.toArray(new Integer[0]));
    }
````

**Comment by TatuLund** [comment]
I have been thinking about this. Both approaches, the current one and your request are justified. Thus I tend to think, that correct place to implement global disabled column list is the application and it should be maintained there. With current implementation of the add-on such list can be given as parameter in event.disableColumns(..).
