### ISSUE TITLE
ClientSide Exception with hidden Columns

### ISSUE THREAD

**Issue by Plonus** [TatuLund/GridFastNavigation#74]
Hello,

with the newest version 2.3.2 we get ClientSide Exceptions (Column not found) when selecting a row.

It is really easy to reproduce, just hide the first column in your demo app, start it and select a row.
![clientside-exception](https://user-images.githubusercontent.com/41110709/42563136-c283514c-84fd-11e8-8a9e-cdc0c5f0c1db.PNG)

**Comment by TatuLund** [comment]
Thank you for reporting this. I need to investigate and debug this deeper. For some reason the exception seem not prevent the add-on working, but clearly I should get rid of it.

**Comment by TatuLund** [comment]
Fixed in version 2.3.3, which is available in directory.
