### ISSUE TITLE
FastNavigation#setFocusedCell sometimes not working

### ISSUE THREAD

**Issue by zsuzsannakokai** [TatuLund/GridFastNavigation#77]
Vaadin Version: 8.5.1
GridFastNavigation.version: 2.3.9

If i call it for (row, column) it is ok. If I call it for (row+1, column) and row+1 represents an Editor row, sometimes focus is not set in Editor Field.

Cases:
1. Editor row represents a new row: works ok
2. Clicking away from the edited row in UI, calling getEditor().editRow() for the edited row from code (since it has invalid data), calling setFocusedCell the same way as in Point 1. - focus is not set, although focus on the previous row works nicely.

**Comment by TatuLund** [comment]
Are you using setRowValidation(true) as well? That has intentional feature to jump focus to first cell having an validation error.

**Comment by zsuzsannakokai** [comment]
No. I tried setRowValidation, it worked ok except for it made Tab to jump only between the required fields. 
I need Tab to jump from field to field in the normal sequence even if the field is not required. That's why I do not use it.

(I hope I remember well - it is sure setRowValidation had some behaviour not fitting for me and I had to avoid it.)

**Comment by TatuLund** [comment]
I made small change in version 2.3.10, the method will now check that row and col are in acceptable range and throws exception if not.

**Comment by TatuLund** [comment]
See also: https://github.com/TatuLund/GridFastNavigation/issues/68#issuecomment-413945580
