### ISSUE TITLE
 enter key move to the next column in the row

### ISSUE THREAD

**Issue by JIMANOPE** [TatuLund/GridFastNavigation#8]
When you press the enter key move to the next column in the row

**Comment by thinwire** [comment]
I'll consider adding this as a mode, but it will require reworking _all_ of the Enter functionality, since it's explicitly been designed to move down (and up with shift pressed) while tab is used to move right (or left with shift pressed).

**Comment by thinwire** [comment]
Update: current architecture is more amenable to this feature. Will try to add the feature once I get a chance to work on this again.

**Comment by TatuLund** [comment]
This has been addressed in version 0.5.2.
