### ISSUE TITLE
Wrong offset with TableSelectionModel from Addon GridExtensionPack

### ISSUE THREAD

**Issue by onlineandy** [TatuLund/GridFastNavigation#82]
When using the Addon [GridExtensionPack ](https://vaadin.com/directory/component/gridextensionpack-add-on)for the Grid in MultiSelect-Mode the column in EditorOpenEvent is off by 1. This is because TableSelectionModel from the addon does not use a checkbox column for selecting the Columns.

I will try to create a PR to fix the offset when the addon is on the classpath.

**Comment by TatuLund** [comment]
Thanks for reporting this issue. It can be tricky corner case. At the moment GridFastNavigation detects whether Grid is in multiselect mode and if yes, it does compensation for internal column counts being off by one. So in case of GridExtensionPack and TableSelectionModel GridFastNavigation should not apply this compensation, but work like in single selection mode. One approach to remedy this issue could be to add API to force GridFastNavigation not to apply the compensation.
