### ISSUE TITLE
RowFocusLstener called twice when grid is not focused and then user click in row

### ISSUE THREAD

**Issue by ldelaprade** [TatuLund/GridFastNavigation#85]
nav.addRowFocusListener
        (
            event
            ->
            {
                lastFocusedRow = event.getRow();

Steps to reproduce : 
my grid has row number x selected (single selection mode grid)
then clicking outside the grid
then clicking inside the grid, row number x+1

symptom: Focus Row Listener function called first with event.getRow() == x+1
then is called again with event.getRow() == x

**Comment by ldelaprade** [comment]
This is a problem because I use the focus listener to force selection to follow the focus...

**Comment by TatuLund** [comment]
I tried to replicate this with the demo app of the add-on. I did the following

- I disabled the editor opening by single click

- I added programmatic selection of one row

- I click outside the grid and then a row, RowFocusEvent is fired only once

I did this testing with Vaadin 8 and latest add-on version.

**Comment by ldelaprade** [comment]
"I added programmatic selection of one row"
Could you please try manual click instead of  programmatic ?
then re-click outside than re-click another row inside
