### ISSUE TITLE
NotSerializableException of OffsetHelper

### ISSUE THREAD

**Issue by elexx** [TatuLund/GridFastNavigation#86]
In our project, we extended the Vaadin 8 Grid and added some functionallity, which is partly provided by GridFastNavigation (kudos to you for this great extension!).
Unfortunatly when serializing a session, that contains a Vaadin UI with our Grid we get a `NotSerializableException` because `OffsetHelper` does not implement `Serializable` but is kept as field in `FastNavigation`:

```
public class FastNavigation<T> extends AbstractExtension {
    private static Logger _logger = Logger.getLogger("FastNavigation");
    private OffsetHelper offsetHelper = new OffsetHelper();
    ...
```
```
public class OffsetHelper {
    ...
```

**Comment by TatuLund** [comment]
Thanks for reporting. This is easy to fix.

**Comment by elexx** [comment]
Yes. I'm about to push a PR ;-)

**Comment by TatuLund** [comment]
I uploaded new version in Directory with fix for this
