### ISSUE TITLE
Different selection behaviour on different servers

### ISSUE THREAD

**Issue by elkebasel** [TatuLund/GridFastNavigation#89]
I implemented FastNavigation for the possibility to move selection by arrow keys which I feel to be really a must-have.
Works fine in local testing (jetty in eclipse and tomee at localhost). On the server (also  with tomee) the selection looks like the fokus and vice versa, and when changing column width the rendering is not OK (the selected row's columns remain unchanged). Without FastNavigation Selection worked normal. 
'

**Comment by TatuLund** [comment]
See discussion here: https://vaadin.com/forum/thread/17488764/fastnavigation-use-keyboard-shortcut-and-arrow-keys-to-deselect-in-multip
