### ISSUE TITLE
Enter key row or column

### ISSUE THREAD

**Issue by JIMANOPE** [TatuLund/GridFastNavigation#9]
Best regard.

As I can enable from the application enter key in rows or columns, I need both options. I have windows with enter key on the rows and others on the columns. Then I would need to make the settings in my application.

Thank you

**Comment by JIMANOPE** [comment]
I was able to activate updating the Keys class by removing rowChangeKeys.add (KeyCodes.KEY_ENTER); And adding colChangeKeys.add (KeyCodes.KEY_ENTER); But if I use one I can not use the other.

I did the following but it did not work

     Public static void addColumnEnter () {
         ColChangeKeys.add (KeyCodes.KEY_ENTER);
         ColChangeKeys.add (KeyCodes.KEY_MAC_ENTER);
     }

     Public static void addRowEnter () {
         RowChangeKeys.add (KeyCodes.KEY_ENTER);
         RowChangeKeys.add (KeyCodes.KEY_MAC_ENTER);
     }

in DemoUI

Keys.addColumnEnter (); But without success

Excuse my English

**Comment by thinwire** [comment]
I see. This isn't a difficult change to make - I'll be keeping the defaults as-is, but more keyboard navigation customization options were planned anyway, so I guess this'll be added to the next release.

**Comment by TatuLund** [comment]
I added this option to version 0.5.2. There is two constructors, the other has additional boolean parameter to configure enter key behavior.
