### ISSUE TITLE
CellFocusEvent is not fired in grid multiselect mode when focus moves to left adjacent cell

### ISSUE THREAD

**Issue by mihalikm93** [TatuLund/GridFastNavigation#95]
Hello,

CellFocusEvent is not fired when the following circumstances apply:
-grid is in multiselect mode
-focus is moved to the left neighboring cell

I believe this is caused by FastNavigation lastFocusedCol being adjusted with an offset, but when checking against it in the focusUpdated function, there is no compensation for offset (FastNavigation.java).

**Comment by TatuLund** [comment]
Yes, I can replicate the problem

**Comment by TatuLund** [comment]
The fix is in version 2.4.6 which I uploaded to Directory a moment ago.

**Comment by mihalikm93** [comment]
Thank you very much for the fast fix!
