### ISSUE TITLE
Issue with focus related to hidden / not editable columns

### ISSUE THREAD

**Issue by mihalikm93** [TatuLund/GridFastNavigation#96]
This problem is probably related to this issue: https://github.com/TatuLund/GridFastNavigation/issues/71

Steps to create a grid which shows the problem:
-first column: visible, not editable (eg. no setter provided)
-second column: hidden, not editable
-third column: visible, editable
-fourth column: visible, editable

Problem 1: double clicking / using the OpenEditorOnTyping feature on the first column should cause the focus to jump to third column. Instead, it jumps to fourth column.

Problem 2: double clicking / using the OpenEditorOnTyping feature on the third column (which should be editable) causes the focus to jump to the fourth column, and starts editing that column instead

**Comment by TatuLund** [comment]
I did myself some testing as well, and I can confirm that in the case of combined hidden and non-editable columns, things go wrong. The current method is flawed. I also think there is no quick adjustment, but I need to rethink it a bit.

**Comment by TatuLund** [comment]
Fixed in 2.5.0

**Comment by mihalikm93** [comment]
Thank you!
