### ISSUE TITLE
Issue with editor mode freezing the browser

### ISSUE THREAD

**Issue by mihalikm93** [TatuLund/GridFastNavigation#98]
hello,

Steps to create a grid which shows the problem:
-first column: editable
-second column: not editable (eg. no setter provided)

Double clicking to open editor mode on the not editable column freezes the browser. Double clicking on the editable column works fine (editor opens as intended), but freezes after you single click on the not editable column in a different row.

Grid selection mode does not seem to affect the problem. (managed to trigger it in single and multiselect mode as well) It might be somehow in relation with specifically the last column not being editable.

**Comment by TatuLund** [comment]
I tried to to reproduce this with the demo app of the add-on as follows

- I commented out the delete button column
- Now first row is editable and second column is not
- I disable opening by single click
- I double click on second column

Result: Editor opens, focus jumps to third column and I can edit it. This is working correctly.

**Comment by mihalikm93** [comment]
Note that there should be no third column. The last column must be the one which is not editable. In other cases I couldn't reproduce the issue.

**Comment by TatuLund** [comment]
Thanks for the clarification, this should be now fixed in version 2.5.1, and I updated it in Directory

**Comment by mihalikm93** [comment]
Thanks, I confirm that the fix is working properly.
