### ISSUE TITLE
isUserOriginated() function for CellFocusEvent

### ISSUE THREAD

**Issue by mihalikm93** [TatuLund/GridFastNavigation#99]
Since cell focus can be changed programmatically, it would be useful if CellFocusEvent could contain that information. I can think of 2 cases when the focus change is considered to be programmatic:

-explicit call to setFocusedCell
-user trying to open editor on a cell which is not editable, thus causing fast navigation to change cell focus to the next editable cell

**Comment by TatuLund** [comment]
Yes, that is true. Also as added editRow(..) method in add-on, also same addition should be done to editor opening event.

**Comment by TatuLund** [comment]
Included in 2.6.0

**Comment by mihalikm93** [comment]
Feature is working, thanks!
